steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/gthl-scraper/scraper:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gthl-scraper/scraper:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'scraper', '--zone=us-east1-b']
