steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/gthl-scraper/scraper']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/gthl-scraper/scraper',
            '--cache-from', 'gcr.io/gthl-scraper/scraper',
            '.'
        ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'scraper', '--project=gthl-scraper']
images: ['gcr.io/gthl-scraper/scraper']
