steps:
- name: gcr.io/kaniko-project/executor:latest
  args: ['--destination=gcr.io/gthl-scraper/scraper',
         '--cache=true']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'scraper', '--zone=us-east1-b']
